const express = require('express');
const router = express.Router();
const homeController = require('../controllers/homeController');
const authRoutes = require('./authRoutes');
const buildingMaterialRoutes = require('./buildingMaterialRoutes');
const buildingMaterialCategoryRoutes = require('./buildingMaterialCategoryRoutes');
const buildingMaterialSeriesRoutes = require('./buildingMaterialSeriesRoutes');
const bmwChatRoutes = require('./bmwChatRoutes');
const messageRoutes = require('./messageRoutes');
const fileUploadRoutes = require('./fileUploadRoutes');
const cartRoutes = require('./cartRoutes');
const orderRoutes = require('./orderRoutes');
const adminUserRoutes = require('./adminUserRoutes');
const adminOrderRoutes = require('./adminOrderRoutes');
const analyticsRoutes = require('./analyticsRoutes');
const commissionRoutes = require('./commissionRoutes');

router.get('/', homeController.getHome);
router.use('/auth', authRoutes);
router.use('/building-materials', buildingMaterialRoutes);
router.use('/building-material-categories', buildingMaterialCategoryRoutes);
router.use('/building-material-series', buildingMaterialSeriesRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/analytics', analyticsRoutes);
router.use('/commissions', commissionRoutes);
router.use('/bmw/chat', bmwChatRoutes);
router.use('/bmw/upload', fileUploadRoutes);
router.use('/messages', messageRoutes);

module.exports = router;
